# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "qurecode"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nicolas Santa"]
  s.date = "2012-05-17"
  s.description = "QRCode generator"
  s.email = "nicolas55ar@gmail.com"
  s.extra_rdoc_files = [
    "README",
    "TODO"
  ]
  s.files = [
    "CHANGELOG",
    "COPYING",
    "README",
    "Rakefile",
    "TODO",
    "VERSION",
    "lib/qr_code_generator.rb",
    "lib/qr_code_generator/core_ext.rb",
    "lib/qr_code_generator/core_ext/array.rb",
    "lib/qr_code_generator/core_ext/core_extensions/core_extensions.rb",
    "lib/qr_code_generator/core_ext/hash.rb",
    "lib/qr_code_generator/core_ext/string.rb",
    "lib/qr_code_generator/qr_code_generator.rb",
    "lib/qr_code_generator/rails.rb",
    "tasks/agiledox.rake",
    "tasks/annotations.rake",
    "test/helpers.rb",
    "test/qr_code_generator_test.rb",
    "test/qr_code_test.rb"
  ]
  s.homepage = "http://github.com/yeti-media/qurecode"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "QRCode generator"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rqrcode>, [">= 0"])
      s.add_runtime_dependency(%q<rmagick>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rake>, ["~> 0.9.2"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<rspec>, [">= 2.6.0"])
    else
      s.add_dependency(%q<rqrcode>, [">= 0"])
      s.add_dependency(%q<rmagick>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rake>, ["~> 0.9.2"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<rspec>, [">= 2.6.0"])
    end
  else
    s.add_dependency(%q<rqrcode>, [">= 0"])
    s.add_dependency(%q<rmagick>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rake>, ["~> 0.9.2"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<rspec>, [">= 2.6.0"])
  end
end

